### PR TITLE
Some card generation tweaks 

### PR DESCRIPTION
**Pull request by anomiex**
These are the changes mentioned in https://www.reddit.com/r/dndnext/comments/51hm37/updated_spell_cards_for_all_srd_spells/ that you requested I send a pull request for.

### CODE REVIEW

**Comment by crobi** [comment]
Thanks for the contribution! I'll leave the PR open, but I won't merge all of it, as I feel the last two commits are a bit of a breaking change for people already using this tool:
- The rule was intentionally rather thick and of triangular shape, so that it looks the same as stat blocks in the monster manual (or https://valloric.github.io/statblock5e/).
- Changing the text size would definitely be a breaking change. Adjusting the text size is already discussed in #44, #45, and #60. Instead of changing the hardcoded size, I'd prefer if it was either a global setting, a per-card setting, or an additional parameter of the `text` element.

**Comment by posita** [comment]
Is this still relevant? Should it be updated/abandoned?

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159

**Comment by posita** [comment]
Closing, since there hasn't been any activity for over a year. @anomiex, please feel free to resolve conflicts and reopen if this is important to you, and I'll work with you to get this merged.

**Pull request closed without merging**
