### PR TITLE
Adding support for a "Savage Worlds" stats and loot blocktype.

### PR DESCRIPTION
**Pull request by fgerling**
Related to issue #83.

### CODE REVIEW

**Comment by posita** [comment]
@crobi, is this worth merging? If you're not going to unblock these merge requests, can you identify and authorize someone who can?

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159

**Comment by posita** [comment]
Closing, since there hasn't been any activity for over three years. @fgerling, if this is important to you, please feel free to reopen so we can see a preview, and I'll work with you to get this merged.

**Comment by fgerling** [comment]
I opened a PR over here, with more details and preview: https://github.com/mephitrpg/rpg-cards/pull/1

If this projects is expecting a revival, I will be more than happy to also "backport" it to this repo.

**Comment by posita** [comment]
> I opened a PR over here, with more details and preview: [mephitrpg#1](https://github.com/mephitrpg/rpg-cards/pull/1)
> 
> If this projects is expecting a revival, I will be more than happy to also "backport" it to this repo.

Unless @mephitrpg is interested in taking over as a collaborator here and merging improvements from his fork before retiring it, I don't think this repo has legs. I don't want to speak for anyone else, but my guess is that [mephitrpg/rpg-cards](https://github.com/mephitrpg/rpg-cards) represents the future of development and that this repo will likely remain as a historical record to honor @crobi's original work. (@crobi and @mephitrpg, please feel free to chime in and contradict any of my speculation.)

That being said, since there was a backlog of PRs here, I thought I'd offer help to folks who were already in line here to move forward any they deemed super important for some reason.

**Pull request closed without merging**
