### PR TITLE
Reupload of Icons with Transparency

### PR DESCRIPTION
**Pull request by garylzimmer**

### CODE REVIEW

**Comment by crobi** [comment]
It looks as if all the files have changed, even the old icons. Did you test that they all work now? Can I merge this without checking myself?

**Comment by garylzimmer** [comment]
It was easier to just redo all of the files than to figure out which did and didn't work. From the diffs that github will bother showing it looks like I fixed a good portion of them if not all.

**Comment by garylzimmer** [comment]
Just tested a good number of icons old and new and they all worked. What doesn't work is the autocompete for new icons, which I have no idea how to fix.

**Comment by crobi** [comment]
> What doesn't work is the autocompete for new icons, which I have no idea how to fix

The autocomplete data is at
https://github.com/crobi/rpg-cards/blob/master/generator/js/icons.js

**Pull request merged**
