### PR TITLE
Added latest icons as at 23 Apr 2016

### LINKED ISSUE #52: Update the list of available icons
There are a lot more available from the website now. I tried to do this myself, but it doesn't look like the way of doing so and the scripts required are all here. E.g. I did not find the script to generate the css for the icons, nor merging in the custom icons not from game-icons.net.

### PR DESCRIPTION
**Pull request by mw-stanley**
Hey, I added the latest icons up to today. This should close #52.

I also removed some erroneous lines from icons.css like a line for filelist.txt and one for list-files.bat.

I'm also going to submit a separate PR on the gh-pages branch to update the docs so they don't say that "all" icons from game-icons are available - since new ones won't be.

### CODE REVIEW

**Comment by crobi** [comment]
Awesome, thanks! I'll update the live preview at https://crobi.github.io/rpg-cards/generator/generate.html as soon as I get to it.

**Comment by garylzimmer** [comment]
Thanks for adding new icons, but they aren't working as far as I can tell. The new icons don't show up in auto-complete and only show as a white box on the live preview and generated page. I can tell it's trying to link to the new image because if I enter 'foo' as an icon name, it shows nothing.

**Comment by garylzimmer** [comment]
I double checked everything and it looks like the new icons lost their transparency. I'll submit a PR with fixed icons.

**Comment by m-stanley** [comment]
Thanks gary - I didn't check them all but I did spot-check a few and they were fine - bicepts, belt, cooking-pot are all fine - but I do see what you're talking about where some of them weren't converted properly - aerodynamic-harpoon, alien-fire, air-zigzag all didn't work. 

Let me get you the details of what I did to convert them so we can find out what I did wrong. It's weird as I did it in a single glob with the mogrify command in [this file](https://github.com/crobi/rpg-cards/blob/master/resources/tools/make-transparent.bat) so surely they should all be affected, or none?

**Comment by mw-stanley** [comment]
Thanks gary - I didn't check them all but I did spot-check a few and they were fine - bicepts, belt, cooking-pot are all fine - but I do see what you're talking about where some of them weren't converted properly - aerodynamic-harpoon, alien-fire, air-zigzag all didn't work.

Let me get you the details of what I did to convert them so we can find out what I did wrong. It's weird as I did it in a single glob with the mogrify command in [this file](https://github.com/crobi/rpg-cards/blob/master/resources/tools/make-transparent.bat) so surely they should all be affected, or none?

(Originally posted this on the wrong account, hah)

**Comment by garylzimmer** [comment]
You did the hard part (redoing the icons.css)
It's actually easier than that!
mogrify -negate *.png

**Pull request merged**
