### PR TITLE
Font + card size enhancements

### PR DESCRIPTION
**Pull request by CarminisVigil**
A few enhancements relating to font + card size (aka, fitting lengthy spell text onto cards):
* Make the "Apply title font" button actually do something and clearly mark the "Apply" buttons as applying to the entire library
* Add an option for full-A4 size cards. (I needed it for a boss) I've used the previous formula of "keep the larger value, double the smaller value + 0.5" to create the size.
* Allow the body text size to be edited - via both default and per-card. I fixed sections/subtitles at body font + 2pts, as I thought that was simpler than making that customisable as well - and when would you want your headings smaller?

### CODE REVIEW

**Comment by CarminisVigil** [comment]
Hold off on this one for now, we've created an issue with the pages sliding off to create extra blank pages. Fix coming soon.

**Comment by JohnMcDaniel** [comment]
I removed the 16px header that wasn't needed on the printer that I was using.

**Comment by posita** [comment]
Is this still relevant? Should it be updated/abandoned?

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159

**Comment by posita** [comment]
Closing, since there hasn't been any activity for over a year. @CarminisVigil, please feel free to resolve conflicts and reopen if this is important to you, and I'll work with you to get this merged.

**Pull request closed without merging**
